# Generated by Django 4.2.20 on 2025-04-26 22:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journal', '0002_alter_profile_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
