# Generated by Django 4.2.20 on 2025-04-27 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='song_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='comment',
            name='song_url',
            field=models.URLField(blank=True),
        ),
    ]
