# Generated by Django 4.2.20 on 2025-05-08 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_comment_song_title_comment_song_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#f3f4f6', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='journalentry',
            name='emotions',
            field=models.ManyToManyField(blank=True, related_name='entries', to='journal.emotion'),
        ),
    ]
