# Generated by Django 4.2.20 on 2025-05-08 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_emotion_journalentry_emotions'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotion',
            name='slug',
            field=models.SlugField(default='temp', unique=True),
        ),
    ]
