# Generated by Django 4.2.20 on 2025-05-08 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0007_emotion_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotion',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
