# Generated by Django 4.2.20 on 2025-05-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_alter_emotion_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='preview_url',
            field=models.URLField(blank=True),
        ),
    ]
