# Generated by Django 4.2.20 on 2025-05-11 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0009_comment_preview_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='preview_url',
        ),
    ]
