# Generated by Django 4.2.20 on 2025-05-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0010_remove_comment_preview_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='song_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='song_url',
            field=models.URLField(blank=True),
        ),
    ]
