# Generated by Django 4.2.20 on 2025-05-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0011_journalentry_song_title_journalentry_song_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='lyric_snippet',
            field=models.TextField(blank=True),
        ),
    ]
