# Generated by Django 4.2.20 on 2025-09-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0015_emotionseed'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='detected_emotion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='detected_keywords',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
