# Generated by Django 4.2.20 on 2025-09-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0016_journalentry_detected_emotion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotion',
            name='spotify_query',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
