# Generated by Django 4.2.20 on 2025-09-23 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journal', '0018_auto_populate_emotions'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, unique_for_date='user')),
                ('song_id', models.CharField(blank=True, max_length=100, null=True)),
                ('song_title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('preview_url', models.URLField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='daily_photos/')),
                ('emotion', models.CharField(choices=[('joy', 'Joy'), ('sadness', 'Sadness'), ('anger', 'Anger'), ('surprise', 'Surprise'), ('anticipation', 'Anticipation')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
