# Generated by Django 4.2.20 on 2025-09-23 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0019_dailyrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyrecord',
            name='date',
        ),
        migrations.AlterField(
            model_name='dailyrecord',
            name='artist',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dailyrecord',
            name='emotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='journal.emotion'),
        ),
        migrations.AlterField(
            model_name='dailyrecord',
            name='song_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dailyrecord',
            name='song_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
