# Generated by Django 4.2.20 on 2025-09-23 10:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journal', '0020_remove_dailyrecord_date_alter_dailyrecord_artist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrecord',
            name='date',
            field=models.DateField(null=True, blank=True),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='dailyrecord',
            unique_together={('user', 'date')},
        ),
    ]
