# Generated by Django 4.2.20 on 2025-09-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0021_dailyrecord_date_alter_dailyrecord_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrecord',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
