# Generated by Django 4.2.20 on 2026-05-13 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0022_alter_dailyrecord_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('category', models.CharField(default='General', max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
