# Generated by Django 4.2.20 on 2026-05-13 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journal', '0023_prompt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompt',
            name='category',
        ),
        migrations.AddField(
            model_name='prompt',
            name='prompt_type',
            field=models.CharField(choices=[('DAILY', 'Daily Song Diary'), ('PREF', 'Preference Profiling')], default='DAILY', max_length=10),
        ),
        migrations.CreateModel(
            name='ProfileAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.prompt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'prompt')},
            },
        ),
    ]
