# Generated by Django 4.2.20 on 2026-05-13 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0024_remove_prompt_category_prompt_prompt_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalentry',
            old_name='content',
            new_name='answer_text',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='detected_emotion',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='detected_keywords',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='hashtags',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='lyric_snippet',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='title',
        ),
        migrations.AddField(
            model_name='journalentry',
            name='prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='journal.prompt'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='emotions',
            field=models.ManyToManyField(blank=True, to='journal.emotion'),
        ),
    ]
