# Generated by Django 4.2.20 on 2026-05-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0025_rename_content_journalentry_answer_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='prompt_type',
            field=models.CharField(choices=[('DAILY', 'Daily Song Diary'), ('PREFERENCE', 'Preference Profiling')], default='DAILY', max_length=10),
        ),
    ]
