# Generated by Django 4.2.20 on 2026-05-28 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0026_alter_prompt_prompt_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='detected_emotion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='detected_keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='lyric_snippet',
            field=models.TextField(blank=True),
        ),
    ]
