databases:
  - name: soundlog-db
    plan: free
    databaseName: soundlog_db
    user: soundlog_db_user

services:
  - type: web
    plan: free
    name: soundlog
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn soundlog.asgi:application -k uvicorn.workers.UvicornWorker' 
